# render.yaml: Configuración de despliegue para la aplicación Validador

services:
  # --- Servicio del Backend (API con Flask) ---
  - type: web
    name: validador-backend
    runtime: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    
    # Comando de inicio con UN SOLO WORKER.
    # Esto es CRÍTICO para evitar que múltiples procesos corrompan la base de datos SQLite.
    startCommand: "gunicorn --workers 1 --bind 0.0.0.0:$PORT run:app"
        
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"
      - key: FLASK_ENV
        value: production
        
      # --- SECRETOS ---
      # Estos valores se configuran en el Dashboard de Render para no exponerlos en el código.
      # `sync: false` evita que Render los sobreescriba.
      - key: SECRET_KEY
        sync: false
      - key: INSTITUTIONAL_ACCESS_KEY
        sync: false
      - key: FRONTEND_URL
        # Render inyectará aquí la URL del frontend automáticamente.
        value: ${validador-frontend.url}

  # --- Servicio del Frontend (Sitio Estático con React) ---
  - type: web
    name: validador-frontend
    runtime: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: build
    
    # --- REGLA DE REESCRITURA (CRÍTICO para SPAs) ---
    routes:
      - type: rewrite
        source: "/*"
        destination: /index.html
        
    envVars:
      # Inyecta la URL del backend en el proceso de build del frontend.
      - key: REACT_APP_API_URL
        value: ${validador-backend.url}